config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'
  resources :users, only: %i[new create show]
  resource :sessions, only: %i[new create show destroy]
  resources :projects
  resources :tasks, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  validates :tittle, presence: true
  has_and_belongs_to_many :tasks
  has_and_belongs_to_many :users
end

app/models/task.rb
class Task < ApplicationRecord
  validates :tittle, presence: true
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :email, format: { with: /@/, message: 'email must contain @' }
  validates :first_name, :second_name, presence: true
  validates :password, presence: true, confirmation: true
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :require_login

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def require_login
    if current_user.blank?
      redirect_to new_sessions_path, notice: 'Need to Login'
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_login

  def index
    @projects = Project.all.where(user_id: current_user.id)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.create(project_params)
    redirect_to project_path(@project.id)
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    redirect_to @project
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to root_path
  end

  private

  def project_params
    params.require(:project).permit(:tittle, :body, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: user_params[:email])
    if @user.blank?
      flash[:warning] = 'wrong password or email'
    elsif @user.password_digest == user_params[:password_digest]
      session[:user_id] = @user.id
      redirect_to user_path(@user.id), notice: 'Вы вошли на сайт'
    else
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password_digest)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.valid?
      user = User.new(user_params)
      if user.save(validate: false)
        session[:user_id] = user.id
        redirect_to "/users/#{user.id}", notice = "Yoy are successfully registered!"
      else
        flash.alert = "Something goes wrong, try later"
      end
    else
      flash.notice = user.errors.full_messages
    end
  end

  def show
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:email, :password_confirmation, :password, :first_name, :second_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskTracker</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <%= javascript_include_tag "application" %>
</head>
<body>
<% if notice %>
  <%= notice %>
<% end %>
<% if alert %>
  <%= alert %>
<% end %>
<div class="user_container">
  <% if @current_user %>
    <%= link_to @current_user.email, @current_user %>
  <% else %>
    <%= button_to "login", new_sessions_path, method: "get" %>
    <%= button_to "signup", new_user_path, method: "get" %>
  <% end %>
</div>
<%= yield %>
</body>
</html>

app/views/projects/edit.html.slim
/ <h2>Редактирование проекта <%= @project.id %></h2>
/ <form action="/projects/#{@project.id}/edit" method="patch">
/   <p>Введите название проекта</p>
/   <p><label><textarea name="@project.tittle"></textarea></label></p>
/   <p>Введите описание проекта</p>
/   <p><label><textarea name="@project.body"></textarea></label></p>
/   <p>Введите id пользователя</p>
/   <p><label><input type="number" name="@project.user_id"></label></p>
/   <p>Введите id проекта</p>
/   <p><label><input type="number" name="@project.id"></label></p>
/   <p><input type='submit' value="Редактировать"></p>
/ </form>

/ Редактирование проекта @project.id
= form_with(model: @project) do |form|
  .mb-3
    = form.label :tittle, class: 'form-label'
    = form.text_field :tittle, class: 'form-control'

  .mb-3
    = form.label :body, class: 'form-label'
    = form.text_area :body, class: 'form-control'

  .mb-3
    = form.submit class: 'btn btn-primary'

app/views/projects/index.erb
<h5>Все проекты</h5>
<% @projects.each do |p|  %>
  <p><%= link_to "Project#{p.id}","/projects/#{p.id}" %></p>
<% end %>

app/views/projects/index.html.slim
h3 Все проекты
= link_to 'New project', 'projects/new', class: 'btn btn-primary'

table.projects_table
  thead
    tr
      th Project
      th Description
      th Created_at
      th Updated_at
  tbody
    - @projects.each do |p|
      tr
        td = link_to p.tittle,"/projects/#{p.id}"
        td = p.body
        td = p.updated_at
        td = p.created_at
        td = button_to "Редактировать", edit_project_path(p.id), method: :get
        td = button_to "Удалить проект", project_path(p.id), method: :delete

app/views/projects/new.html.slim
h2 Создание проекта

= form_with(model: @project) do |form|
  .mb-3
    = form.label :tittle, class: "form-label"
    = form.text_area :tittle, class: "form-control"

  .mb-3
    = form.label :description, class: "form-label"
    = form.text_area :body, class: "form-control"

  .mb-3
    = form.submit "Create", class: "btn btn-primary"

app/views/projects/show.html.slim
/ <p>Заголовок: <%= @project.tittle  %></p>
/ <p>Описание: <%= @project.body  %></p>
/ <p><%= button_to 'Редактировать', edit_project_path(@project.id) %></p>
/ <p><%= button_to 'Удалить проект', project_path(@project.id), method: :delete %></p>
/ <p><%= button_to 'Все проекты', '/projects', method: :get %></p>

h3 = @project.tittle
p = @project.body

div
  = button_to 'Редактировать', edit_project_path(@project.id), method: :get
  = button_to 'Удалить проект', project_path(@project.id), method: :delete
  = button_to 'Все проекты', '/projects', method: :get

app/views/users/_form.html.slim
= form_with(model: user) do |form|
  .mb-3
    = form.label :email, class: "form-label"
    = form.text_field :email, class: "form-control"

  .mb-3
    = form.label :first_name, class: "form-label"
    = form.text_field :first_name, class: "form-control"

  .mb-3
    = form.label :second_name, class: "form-label"
    = form.text_field :second_name, class: "form-control"

  .mb-3
    = form.label :password, class: "form-label"
    = form.password_field :password, class: "form-control"

  .mb-3
    = form.label :password_confirmation, class: "form-label"
    = form.password_field :password_confirmation, class: "form-control"

  .mb-3
    = form.submit "Log in", class: "btn btn-primary"

app/views/users/new.html.slim
h3 Sign Up
= render 'form', user: @user

app/views/users/show.html.slim
h3 = @user.email